id: IFCF548FF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:33:57+00:00'
last_modified: '2022-06-08T13:18:40.556682+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5532
  title: རྟག་ཏུ་ངུའི་རྟོགས་བརྗོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    872E:
      image_group_id: I3CN5534
      title: ''
      total_pages: 212
      order: 1
      base_file: 872E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
