id: P010399
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:47:46.458895
source_metadata:
  id: bdr:W3CN5532
  title: རྟག་ཏུ་ངུའི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    ae6ad5c4bb7a4d88a9ab5029d0edfa4f:
      image_group_id: I3CN5534
      title: ''
      volume_number: 1
      total_pages: 212
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
